AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: LINE Reminder Bot with SAM

Parameters:
  LineChannelAccessToken:
    Type: String
    Description: LINE Channel Access Token
  LineChannelSecret:
    Type: String
    Description: LINE Channel Secret

Globals:
  Function:
    Timeout: 29
    Runtime: nodejs16.x
    Environment:
      Variables:
        LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
        LINE_CHANNEL_SECRET: !Ref LineChannelSecret
        DYNAMODB_TABLE: !Ref RemindersTable

Resources:
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/webhook.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

  CheckRemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/check-reminders.handler
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  RemindersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

Outputs:
  WebhookApi:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"