AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  LineChannelSecret:
    Type: String
  LineChannelAccessToken:
    Type: String

Resources:
  LineWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: webhook.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          LINE_CHANNEL_SECRET: !Ref LineChannelSecret
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

  ReminderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/
      Handler: reminder.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          LINE_CHANNEL_ACCESS_TOKEN: !Ref LineChannelAccessToken
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

  RemindersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Reminders
      AttributeDefinitions:
        - AttributeName: group_id
          AttributeType: S
        - AttributeName: reminder_id
          AttributeType: S
      KeySchema:
        - AttributeName: group_id
          KeyType: HASH
        - AttributeName: reminder_id
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES